version: "3.2"

services:
  dev:
    container_name: kahawa
    image: paritytech/ci-linux:974ba3ac-20201006
    working_dir: /var/www/kahawa
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/kahawa/.cargo
    volumes:
      - .:/var/www/kahawa
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --release && ./target/release/kahawa --dev --ws-external"
